version: '3'
services:
    nginx:
        restart: always
        image: nginx:latest
        network_mode: host
        volumes:
            - ./nginx/logs:/tmp/logs
            - ./nginx/config:/etc/nginx/conf.d
        depends_on:
            - trollblock
    trollblock:
        restart: always
        build: .
        network_mode: host